version: 0.0
os: linux
files:
  - source: www/
    destination: /var/www/html/
hooks:
  ApplicationStart:
    - location: scripts/say_hello.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/say_goodbye.sh
      timeout: 300
      runas: root
